/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui.research_view;

/**
 *
 * @author Lexi
 */
class WoodworkingForm extends javax.swing.JPanel
{

    /**
     * Creates new form WoodworkingForm
     */
    private WoodworkingForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        weaponPane = new javax.swing.JScrollPane();
        weaponTable = new javax.swing.JTable();
        apparelPane = new javax.swing.JScrollPane();
        apparelTable = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        weaponTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Énergisé", null, null, null, null, null},
                {"Chargé", null, null, null, null, null},
                {"Précis", null, null, null, null, null},
                {"Infusé", null, null, null, null, null},
                {"Défenseur", null, null, null, null, null},
                {"Entrainement", null, null, null, null, null},
                {"Acéré", null, null, null, null, null},
                {"Décisif", null, null, null, null, null},
                {"Trempe de Nirn", null, null, null, null, null}
            },
            new String []
            {
                "Arme", "Arc", "Bâton Infernal", "Bâton de Glace", "Bâton de Foudre", "Bâton de Rétablissement"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        weaponTable.getTableHeader().setReorderingAllowed(false);
        weaponPane.setViewportView(weaponTable);
        if (weaponTable.getColumnModel().getColumnCount() > 0)
        {
            weaponTable.getColumnModel().getColumn(0).setResizable(false);
            weaponTable.getColumnModel().getColumn(1).setResizable(false);
            weaponTable.getColumnModel().getColumn(2).setResizable(false);
            weaponTable.getColumnModel().getColumn(3).setResizable(false);
            weaponTable.getColumnModel().getColumn(4).setResizable(false);
            weaponTable.getColumnModel().getColumn(5).setResizable(false);
        }

        apparelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Solide", null},
                {"Impénétrable", null},
                {"Renforcé", null},
                {"Ajusté", null},
                {"Entraînement", null},
                {"Infusé", null},
                {"Prospère", null},
                {"Divins", null},
                {"Trempe de Nirn", null}
            },
            new String []
            {
                "Armure", "Bouclier"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        apparelPane.setViewportView(apparelTable);
        if (apparelTable.getColumnModel().getColumnCount() > 0)
        {
            apparelTable.getColumnModel().getColumn(0).setResizable(false);
            apparelTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apparelPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(weaponPane, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(weaponPane, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(apparelPane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    static WoodworkingForm getInstance()
    {
        WoodworkingForm instance = WoodworkingForm.INSTANCE;
        if (instance == null)
        {
            synchronized (WoodworkingForm.class)
            {
                instance = WoodworkingForm.INSTANCE;
                if (instance == null)
                {
                    WoodworkingForm.INSTANCE = instance = new WoodworkingForm();
                }
            }
        }
        return instance;
    }

    // <editor-fold defaultstate="collapsed" desc="importTables Code">
    static void importTables(ResearchViewData.woodworkingTableModel tables)
    {
        app.gui.thread.TableRenderer.addOperation(tables.getApparelTable(), getInstance().apparelTable);
        app.gui.thread.TableRenderer.addOperation(tables.getWeaponTable(), getInstance().weaponTable);
    }// </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="retrieveTables Code">
    static ResearchViewData.woodworkingTableModel retrieveTables()
    {
        ResearchViewData.woodworkingTableModel tables = new ResearchViewData.woodworkingTableModel();
        tables.setApparelTable(getInstance().apparelTable.getModel());
        tables.setWeaponTable(getInstance().weaponTable.getModel());
        return tables;
    }// </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane apparelPane;
    private javax.swing.JTable apparelTable;
    private javax.swing.JScrollPane weaponPane;
    private javax.swing.JTable weaponTable;
    // End of variables declaration//GEN-END:variables

    private static volatile WoodworkingForm INSTANCE;
}
