/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui.library_view;

/**
 *
 * @author Lexi
 */
class CyrodiilForm extends javax.swing.JPanel
{

    /**
     * Creates new form CyrodiilForm
     */
    private CyrodiilForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        xivkynStylePane = new javax.swing.JScrollPane();
        xivkynStyleTable = new javax.swing.JTable();
        akaviriStylePane = new javax.swing.JScrollPane();
        akaviriStyleTable = new javax.swing.JTable();
        allianceStylePane = new javax.swing.JScrollPane();
        allianceStyleTable = new javax.swing.JTable();
        dominionStylePane = new javax.swing.JScrollPane();
        dominionStyleTable = new javax.swing.JTable();
        pactStylePane = new javax.swing.JScrollPane();
        pactStyleTable = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        xivkynStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 17, Ch. 1 : Les Haches Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 2 : Les Ceintures Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 3 : Les Bottes Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 4 : Les Arcs Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 5 : Les Plastrons Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 6 : Les Dagues Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 7 : Les Gants Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 8 : Les Casques Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 9 : Les Jambières Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 10 : Les Masses Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 11 : Les Boucliers Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 12 : Les Épaulières Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 13 : Les Bâtons Xivkyn", null},
                {"Motifs Artisanaux 17, Ch. 14 : Les Épées Xivkyn", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        xivkynStyleTable.getTableHeader().setReorderingAllowed(false);
        xivkynStylePane.setViewportView(xivkynStyleTable);
        if (xivkynStyleTable.getColumnModel().getColumnCount() > 0)
        {
            xivkynStyleTable.getColumnModel().getColumn(0).setResizable(false);
            xivkynStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            xivkynStyleTable.getColumnModel().getColumn(1).setResizable(false);
            xivkynStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        akaviriStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 18, Ch. 1 : Les Haches Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 2 : Les Ceintures Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 3 : Les Bottes Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 4 : Les Arcs Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 5 : Les Plastrons Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 6 : Les Dagues Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 7 : Les Gants Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 8 : Les Casques Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 9 : Les Jambières Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 10 : Les Masses Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 11 : Les Boucliers Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 12 : Les Épaulières Akaviroises", null},
                {"Motifs Artisanaux 18, Ch. 13 : Les Bâtons Akavirois", null},
                {"Motifs Artisanaux 18, Ch. 14 : Les Épées Akaviroises", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        akaviriStyleTable.getTableHeader().setReorderingAllowed(false);
        akaviriStylePane.setViewportView(akaviriStyleTable);
        if (akaviriStyleTable.getColumnModel().getColumnCount() > 0)
        {
            akaviriStyleTable.getColumnModel().getColumn(0).setResizable(false);
            akaviriStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            akaviriStyleTable.getColumnModel().getColumn(1).setResizable(false);
            akaviriStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        allianceStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 26, Ch. 1 : Les Haches de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 2 : Les Ceintures de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 3 : Les Bottes de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 4 : Les Arcs de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 5 : Les Plastrons de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 6 : Les Dagues de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 7 : Les Gants de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 8 : Les Casques de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 9 : Les Jambières de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 10 : Les Masses de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 11 : Les Boucliers de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 12 : Les Épaulières de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 13 : Les Bâtons de l'Alliance", null},
                {"Motifs Artisanaux 26, Ch. 14 : Les Épées de l'Alliance", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        allianceStyleTable.getTableHeader().setReorderingAllowed(false);
        allianceStylePane.setViewportView(allianceStyleTable);
        if (allianceStyleTable.getColumnModel().getColumnCount() > 0)
        {
            allianceStyleTable.getColumnModel().getColumn(0).setResizable(false);
            allianceStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            allianceStyleTable.getColumnModel().getColumn(1).setResizable(false);
            allianceStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        dominionStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 25, Ch. 1 : Les Haches du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 2 : Les Ceintures du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 3 : Les Bottes du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 4 : Les Arcs du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 5 : Les Plastrons du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 6 : Les Dagues du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 7 : Les Gants du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 8 : Les Casques du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 9 : Les Jambières du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 10 : Les Masses du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 11 : Les Boucliers du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 12 : Les Épaulières du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 13 : Les Bâtons du Domaine", null},
                {"Motifs Artisanaux 25, Ch. 14 : Les Épées du Domaine", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        dominionStyleTable.getTableHeader().setReorderingAllowed(false);
        dominionStylePane.setViewportView(dominionStyleTable);
        if (dominionStyleTable.getColumnModel().getColumnCount() > 0)
        {
            dominionStyleTable.getColumnModel().getColumn(0).setResizable(false);
            dominionStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            dominionStyleTable.getColumnModel().getColumn(1).setResizable(false);
            dominionStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        pactStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 27, Ch. 1 : Les Haches du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 2 : Les Ceintures du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 3 : Les Bottes du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 4 : Les Arcs du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 5 : Les Plastrons du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 6 : Les Dagues du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 7 : Les Gants du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 8 : Les Casques du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 9 : Les Jambières du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 10 : Les Masses du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 11 : Les Boucliers du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 12 : Les Épaulières du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 13 : Les Bâtons du Pacte", null},
                {"Motifs Artisanaux 27, Ch. 14 : Les Épées du Pacte", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        pactStyleTable.getTableHeader().setReorderingAllowed(false);
        pactStylePane.setViewportView(pactStyleTable);
        if (pactStyleTable.getColumnModel().getColumnCount() > 0)
        {
            pactStyleTable.getColumnModel().getColumn(0).setResizable(false);
            pactStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            pactStyleTable.getColumnModel().getColumn(1).setResizable(false);
            pactStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xivkynStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(akaviriStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dominionStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allianceStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pactStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xivkynStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akaviriStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allianceStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dominionStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pactStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    static CyrodiilForm getInstance()
    {
        CyrodiilForm instance = CyrodiilForm.INSTANCE;
        if (instance == null)
        {
            synchronized (CyrodiilForm.class)
            {
                instance = CyrodiilForm.INSTANCE;
                if (instance == null)
                {
                    CyrodiilForm.INSTANCE = instance = new CyrodiilForm();
                }
            }
        }
        return instance;
    }

    // <editor-fold defaultstate="collapsed" desc="importTables Code">
    static void importTables(LibraryViewData.cyrodiilTableModel tables)
    {
        app.gui.thread.TableRenderer.addOperation(tables.getAkaviriTable(), getInstance().akaviriStyleTable);
        app.gui.thread.TableRenderer.addOperation(tables.getAllianceTable(), getInstance().allianceStyleTable);
        app.gui.thread.TableRenderer.addOperation(tables.getDominionTable(), getInstance().dominionStyleTable);
        app.gui.thread.TableRenderer.addOperation(tables.getPactTable(), getInstance().pactStyleTable);
        app.gui.thread.TableRenderer.addOperation(tables.getXivkynTable(), getInstance().xivkynStyleTable);
    }// </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="retrieveTables Code">
    static LibraryViewData.cyrodiilTableModel retrieveTables()
    {
        LibraryViewData.cyrodiilTableModel tables = new LibraryViewData.cyrodiilTableModel();
        tables.setAkaviriTable(getInstance().akaviriStyleTable.getModel());
        tables.setAllianceTable(getInstance().allianceStyleTable.getModel());
        tables.setDominionTable(getInstance().dominionStyleTable.getModel());
        tables.setPactTable(getInstance().pactStyleTable.getModel());
        tables.setXivkynTable(getInstance().xivkynStyleTable.getModel());
        return tables;
    }// </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane akaviriStylePane;
    private javax.swing.JTable akaviriStyleTable;
    private javax.swing.JScrollPane allianceStylePane;
    private javax.swing.JTable allianceStyleTable;
    private javax.swing.JScrollPane dominionStylePane;
    private javax.swing.JTable dominionStyleTable;
    private javax.swing.JScrollPane pactStylePane;
    private javax.swing.JTable pactStyleTable;
    private javax.swing.JScrollPane xivkynStylePane;
    private javax.swing.JTable xivkynStyleTable;
    // End of variables declaration//GEN-END:variables

    private static volatile CyrodiilForm INSTANCE;
}
