/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui.library_view;

/**
 *
 * @author Lexi
 */
class ThievesGuildForm extends javax.swing.JPanel
{

    /**
     * Creates new form ThievesGuildForm
     */
    private ThievesGuildForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        outlawStylePane = new javax.swing.JScrollPane();
        outlawStyleTable = new javax.swing.JTable();
        abahWatchStylePane = new javax.swing.JScrollPane();
        abahWatchStyleTable = new javax.swing.JTable();
        dromAthraStylePane = new javax.swing.JScrollPane();
        dromAthraStyleTable = new javax.swing.JTable();
        thievesGuildStylePane = new javax.swing.JScrollPane();
        thievesGuildStyleTable = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        outlawStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 24, Ch. 1 : Les Haches de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 2 : Les Ceintures de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 3 : Les Bottes de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 4 : Les Arcs de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 5 : Les Plastrons de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 6 : Les Dagues de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 7 : Les Gants de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 8 : Les Casques de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 9 : Les Jambières de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 10 : Les Masses de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 11 : Les Boucliers de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 12 : Les Épaulières de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 13 : Les Bâtons de Hors-la-loi", null},
                {"Motifs Artisanaux 24, Ch. 14 : Les Épées de Hors-la-loi", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        outlawStyleTable.getTableHeader().setReorderingAllowed(false);
        outlawStylePane.setViewportView(outlawStyleTable);
        if (outlawStyleTable.getColumnModel().getColumnCount() > 0)
        {
            outlawStyleTable.getColumnModel().getColumn(0).setResizable(false);
            outlawStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            outlawStyleTable.getColumnModel().getColumn(1).setResizable(false);
            outlawStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        abahWatchStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 32, Ch. 1 : Les Haches de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 2 : Les Ceintures de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 3 : Les Bottes de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 4 : Les Arcs de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 5 : Les Plastrons de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 6 : Les Dagues de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 7 : Les Gants de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 8 : Les Casques de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 9 : Les Jambières de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 10 : Les Masses de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 11 : Les Boucliers de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 12 : Les Épaulières de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 13 : Les Bâtons de la Garde d'Abah", null},
                {"Motifs Artisanaux 32, Ch. 14 : Les Épées de la Garde d'Abah", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        abahWatchStyleTable.getTableHeader().setReorderingAllowed(false);
        abahWatchStylePane.setViewportView(abahWatchStyleTable);
        if (abahWatchStyleTable.getColumnModel().getColumnCount() > 0)
        {
            abahWatchStyleTable.getColumnModel().getColumn(0).setResizable(false);
            abahWatchStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            abahWatchStyleTable.getColumnModel().getColumn(1).setResizable(false);
            abahWatchStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        dromAthraStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 35, Ch. 1 : Les Haches Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 2 : Les Ceintures Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 3 : Les Bottes Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 4 : Les Arcs Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 5 : Les Plastrons Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 6 : Les Dagues Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 7 : Les Gants Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 8 : Les Casques Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 9 : Les Jambières Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 10 : Les Masses Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 11 : Les Boucliers Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 12 : Les Épaulières Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 13 : Les Bâtons Dro-m'Athra", null},
                {"Motifs Artisanaux 35, Ch. 14 : Les Épées Dro-m'Athra", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        dromAthraStyleTable.getTableHeader().setReorderingAllowed(false);
        dromAthraStylePane.setViewportView(dromAthraStyleTable);
        if (dromAthraStyleTable.getColumnModel().getColumnCount() > 0)
        {
            dromAthraStyleTable.getColumnModel().getColumn(0).setResizable(false);
            dromAthraStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            dromAthraStyleTable.getColumnModel().getColumn(1).setResizable(false);
            dromAthraStyleTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        }

        thievesGuildStyleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Motifs Artisanaux 33, Ch. 1 : Les Haches de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 2 : Les Ceintures de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 3 : Les Bottes de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 4 : Les Arcs de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 5 : Les Plastrons de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 6 : Les Dagues de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 7 : Les Gants de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 8 : Les Casques de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 9 : Les Jambières de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 10 : Les Masses de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 11 : Les Boucliers de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 12 : Les Épaulières de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 13 : Les Bâtons de la Guilde des Voleurs", null},
                {"Motifs Artisanaux 33, Ch. 14 : Les Épées de la Guilde des Voleurs", null}
            },
            new String []
            {
                "", ""
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        thievesGuildStyleTable.getTableHeader().setReorderingAllowed(false);
        thievesGuildStylePane.setViewportView(thievesGuildStyleTable);
        if (thievesGuildStyleTable.getColumnModel().getColumnCount() > 0)
        {
            thievesGuildStyleTable.getColumnModel().getColumn(0).setResizable(false);
            thievesGuildStyleTable.getColumnModel().getColumn(0).setPreferredWidth(350);
            thievesGuildStyleTable.getColumnModel().getColumn(1).setResizable(false);
            thievesGuildStyleTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outlawStylePane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addComponent(thievesGuildStylePane))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abahWatchStylePane, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dromAthraStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outlawStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abahWatchStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dromAthraStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thievesGuildStylePane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    static ThievesGuildForm getInstance()
    {
        ThievesGuildForm instance = ThievesGuildForm.INSTANCE;
        if (instance == null)
        {
            synchronized (ThievesGuildForm.class)
            {
                instance = ThievesGuildForm.INSTANCE;
                if (instance == null)
                {
                    ThievesGuildForm.INSTANCE = instance = new ThievesGuildForm();
                }
            }
        }
        return instance;
    }

    static void importTables(LibraryViewData.thievesGuildTableModel thievesGuildTableModel)
    {
        java.util.Vector abahWatchData = thievesGuildTableModel.getAbahWatchTable();
        for (int i = 0; i < abahWatchData.size(); ++i)
        {
            for (int j = 1; j < ((java.util.Vector) abahWatchData.elementAt(i)).size(); ++j)
            {
                getInstance().abahWatchStyleTable.setValueAt(((java.util.Vector) abahWatchData.elementAt(i)).elementAt(j), i, j);
            }
        }
        java.util.Vector dromAthraData = thievesGuildTableModel.getDromAthraTable();
        for (int i = 0; i < dromAthraData.size(); ++i)
        {
            for (int j = 1; j < ((java.util.Vector) dromAthraData.elementAt(i)).size(); ++j)
            {
                getInstance().dromAthraStyleTable.setValueAt(((java.util.Vector) dromAthraData.elementAt(i)).elementAt(j), i, j);
            }
        }
        java.util.Vector outlawData = thievesGuildTableModel.getOutlawTable();
        for (int i = 0; i < outlawData.size(); ++i)
        {
            for (int j = 1; j < ((java.util.Vector) outlawData.elementAt(i)).size(); ++j)
            {
                getInstance().outlawStyleTable.setValueAt(((java.util.Vector) outlawData.elementAt(i)).elementAt(j), i, j);
            }
        }
        java.util.Vector thievesGuildData = thievesGuildTableModel.getThievesGuildTable();
        for (int i = 0; i < thievesGuildData.size(); ++i)
        {
            for (int j = 1; j < ((java.util.Vector) thievesGuildData.elementAt(i)).size(); ++j)
            {
                getInstance().thievesGuildStyleTable.setValueAt(((java.util.Vector) thievesGuildData.elementAt(i)).elementAt(j), i, j);
            }
        }
    }

    static LibraryViewData.thievesGuildTableModel retrieveTables()
    {
        LibraryViewData.thievesGuildTableModel tables = new LibraryViewData.thievesGuildTableModel();
        tables.setAbahWatchTable(getInstance().abahWatchStyleTable.getModel());
        tables.setDromAthraTable(getInstance().dromAthraStyleTable.getModel());
        tables.setOutlawTable(getInstance().outlawStyleTable.getModel());
        tables.setThievesGuildTable(getInstance().thievesGuildStyleTable.getModel());
        return tables;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane abahWatchStylePane;
    private javax.swing.JTable abahWatchStyleTable;
    private javax.swing.JScrollPane dromAthraStylePane;
    private javax.swing.JTable dromAthraStyleTable;
    private javax.swing.JScrollPane outlawStylePane;
    private javax.swing.JTable outlawStyleTable;
    private javax.swing.JScrollPane thievesGuildStylePane;
    private javax.swing.JTable thievesGuildStyleTable;
    // End of variables declaration//GEN-END:variables

    private static volatile ThievesGuildForm INSTANCE;
}
